services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
# 一旦用自己的image 就会少很多api
#    image: jxxxuan/x-tv:latest
#    container_name: x-tv
    ports:
      - "8899:8080" # 将内部 8080 端口映射到主机的 8899 端口
    environment:
      - PASSWORD=${PASSWORD:-your_password} # 可将 your_password 修改为你想要的密码，默认为 your_password
#    volumes:
#      - libretv_data:/app # 不要修改
    restart: unless-stopped

  xuantv-dev:
    build: .
    container_name: xuantv-dev
    ports:
      - "8898:8080"
    volumes:
    - .:/app
    - /app/node_modules   # 把当前目录映射到容器 /app

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}

#volumes:
#  libretv_data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${PWD:-.}/data # 可将 ${PWD:-.} 修改为你想要的路径，默认为当前目录下的 data 文件夹